parameters:
    theodo_map.friend_manager.class: Theodo\MapBundle\Manager\FriendManager

services:
    theodo_map.friend_manager:
        class: %theodo_map.friend_manager.class%
        arguments: [@fos_facebook.api]
