parameters:
#    theodo_map.example.class: Theodo\MapBundle\Example

services:
#    theodo_map.example:
#        class: %theodo_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
